### ISSUE TITLE
Hạ target netframework xuống version thấp hơn

### ISSUE THREAD

**Issue by xuandung38** [drnxloc/AutoLDPlayer#1]
Mình thấy hiện tại bạn đang để target là 4.8 , mình nghĩ bạn nên hạ xuống ver thấp hơn để anh em cài đỡ lỗi, nhiều ae vẫn đang xài 4.6.x thậm chí 4.5.x

**Comment by drnxloc** [comment]
oki

Vào Th 2, 4 thg 1, 2021 vào lúc 14:27 HXD <notifications@github.com> đã
viết:

**Comment by yeucodonvn** [comment]
hiện tại e thấy win 7 vẫn là 4.5 nên hạ xuống đó d thì tốt quá ạ
