### ISSUE TITLE
Tap_Img will miss cvextern.dll

### ISSUE THREAD

**Issue by ontisme** [drnxloc/AutoLDPlayer#3]
I reference this library from Nuget, when I use `Tap_Img`, I get an error

"Exception occurred in type initializer for Emgu.CV.CvInvoke'"
"DllNotFoundException: Unable to load DLL 'cvextern': The specified module could not be found. (Exception occurred at HRESULT: 0x8007007E)"

You must download emgu.cv and take out the file `cvextern.dll` and put it in the root directory of the program to work properly

[cvextern.zip](https://github.com/drnxloc/AutoLDPlayer/files/8789972/cvextern.zip)

**Comment by drnxloc** [comment]
thanks
