### ISSUE TITLE
i have some error  Emgu.CV.World

### ISSUE THREAD

**Issue by tonzsm** [drnxloc/AutoLDPlayer#5]
![image](https://github.com/drnxloc/AutoLDPlayer/assets/19351017/9eeed1b7-8a38-443c-99b8-939ab639e06c)

how to fix this ?

**Comment by drnxloc** [comment]
Fixed [5c16ad2](https://github.com/drnxloc/AutoLDPlayer/commit/5c16ad22603159d37ac5454a29f4abdc7ffd39fa) you can update the new version 1.1.0 to fix it.
