### ISSUE TITLE
Emgu.CV.World issue 

### ISSUE THREAD

**Issue by PaZIVAL0001** [drnxloc/AutoLDPlayer#8]
![image](https://github.com/drnxloc/AutoLDPlayer/assets/91155214/8e6a8709-6b93-4ab3-aceb-a9be151d770b)

how to fix this issue.

**Comment by drnxloc** [comment]
Fixed [5c16ad2](https://github.com/drnxloc/AutoLDPlayer/commit/5c16ad22603159d37ac5454a29f4abdc7ffd39fa) you can update the new version 1.1.0 to fix it.
